FROM nginx
LABEL MAINTAINER "Your name"
ENV MY_HOST localhost
COPY dotask.sh /
RUN apt-get update && apt-get install -y git sed
RUN mkdir /mycode && cd /mycode && git clone https://github.com/apichonsiit/testgit.git
RUN cp -r /mycode/testgit/src /usr/share/nginx/html/mygitweb
CMD ["sh","/dotask.sh"]
